development:
        adapter: postgresql
        encoding: SQL_ASCII
        database: mysite_development
        pool: 5
        username: ubuntu
        password: password
        timeout: 5000  

test:
  adapter: postgresql
  database: mysite_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mysite_production
  pool: 5
  timeout: 5000
  
       